/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerToolsRouteImport } from './routes/viewer-tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchToolsRouteImport } from './routes/research-tools'
import { Route as DatasetToolsRouteImport } from './routes/dataset-tools'
import { Route as CreateJobRouteImport } from './routes/create-job'
import { Route as ConvexRouteImport } from './routes/convex'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const ViewerToolsRoute = ViewerToolsRouteImport.update({
  id: '/viewer-tools',
  path: '/viewer-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchToolsRoute = ResearchToolsRouteImport.update({
  id: '/research-tools',
  path: '/research-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetToolsRoute = DatasetToolsRouteImport.update({
  id: '/dataset-tools',
  path: '/dataset-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateJobRoute = CreateJobRouteImport.update({
  id: '/create-job',
  path: '/create-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvexRoute = ConvexRouteImport.update({
  id: '/convex',
  path: '/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convex': typeof ConvexRoute
  '/create-job': typeof CreateJobRoute
  '/dataset-tools': typeof DatasetToolsRoute
  '/research-tools': typeof ResearchToolsRoute
  '/settings': typeof SettingsRoute
  '/viewer-tools': typeof ViewerToolsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convex': typeof ConvexRoute
  '/create-job': typeof CreateJobRoute
  '/dataset-tools': typeof DatasetToolsRoute
  '/research-tools': typeof ResearchToolsRoute
  '/settings': typeof SettingsRoute
  '/viewer-tools': typeof ViewerToolsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/jobs': typeof JobsIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convex': typeof ConvexRoute
  '/create-job': typeof CreateJobRoute
  '/dataset-tools': typeof DatasetToolsRoute
  '/research-tools': typeof ResearchToolsRoute
  '/settings': typeof SettingsRoute
  '/viewer-tools': typeof ViewerToolsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convex'
    | '/create-job'
    | '/dataset-tools'
    | '/research-tools'
    | '/settings'
    | '/viewer-tools'
    | '/jobs/$jobId'
    | '/results/$id'
    | '/jobs/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convex'
    | '/create-job'
    | '/dataset-tools'
    | '/research-tools'
    | '/settings'
    | '/viewer-tools'
    | '/jobs/$jobId'
    | '/results/$id'
    | '/jobs'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/convex'
    | '/create-job'
    | '/dataset-tools'
    | '/research-tools'
    | '/settings'
    | '/viewer-tools'
    | '/jobs/$jobId'
    | '/results/$id'
    | '/jobs/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvexRoute: typeof ConvexRoute
  CreateJobRoute: typeof CreateJobRoute
  DatasetToolsRoute: typeof DatasetToolsRoute
  ResearchToolsRoute: typeof ResearchToolsRoute
  SettingsRoute: typeof SettingsRoute
  ViewerToolsRoute: typeof ViewerToolsRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ResultsIdRoute: typeof ResultsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer-tools': {
      id: '/viewer-tools'
      path: '/viewer-tools'
      fullPath: '/viewer-tools'
      preLoaderRoute: typeof ViewerToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-tools': {
      id: '/research-tools'
      path: '/research-tools'
      fullPath: '/research-tools'
      preLoaderRoute: typeof ResearchToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset-tools': {
      id: '/dataset-tools'
      path: '/dataset-tools'
      fullPath: '/dataset-tools'
      preLoaderRoute: typeof DatasetToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-job': {
      id: '/create-job'
      path: '/create-job'
      fullPath: '/create-job'
      preLoaderRoute: typeof CreateJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convex': {
      id: '/convex'
      path: '/convex'
      fullPath: '/convex'
      preLoaderRoute: typeof ConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvexRoute: ConvexRoute,
  CreateJobRoute: CreateJobRoute,
  DatasetToolsRoute: DatasetToolsRoute,
  ResearchToolsRoute: ResearchToolsRoute,
  SettingsRoute: SettingsRoute,
  ViewerToolsRoute: ViewerToolsRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ResultsIdRoute: ResultsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
